// components/layout/Footer.tsx
export function Footer() {
  return (
    <footer className="bg-gray-900 text-white">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
          {/* Brand Section */}
          <div className="md:col-span-1">
            <a 
              href="/" 
              className="text-2xl font-bold text-white hover:text-indigo-300 transition-colors duration-300 focus:outline-none focus:ring-2 focus:ring-indigo-400 focus:ring-offset-2 focus:ring-offset-gray-900 rounded-md px-1"
              aria-label="HVFLVSPOT homepage"
            >
              HVFLVSPOT
            </a>
            <p className="mt-4 text-gray-400 text-sm leading-relaxed">
              Discover and book tickets for the best events near you. Your perfect experience is just a click away.
            </p>
          </div>

          {/* Navigation Links */}
          <div className="md:col-span-2">
            <div className="grid grid-cols-2 gap-8">
              {/* Company Links */}
              <div>
                <h3 className="text-sm font-semibold text-white uppercase tracking-wider mb-4">
                  Company
                </h3>
                <nav className="space-y-3" aria-label="Company navigation">
                  <a 
                    href="/about" 
                    className="footer-link"
                    aria-label="Learn more about HVFLVSPOT"
                  >
                    About Us
                  </a>
                  <a 
                    href="/contact" 
                    className="footer-link"
                    aria-label="Contact HVFLVSPOT support"
                  >
                    Contact
                  </a>
                  <a 
                    href="/careers" 
                    className="footer-link"
                    aria-label="View career opportunities"
                  >
                    Careers
                  </a>
                  <a 
                    href="/blog" 
                    className="footer-link"
                    aria-label="Read our blog"
                  >
                    Blog
                  </a>
                </nav>
              </div>

              {/* Legal Links */}
              <div>
                <h3 className="text-sm font-semibold text-white uppercase tracking-wider mb-4">
                  Legal
                </h3>
                <nav className="space-y-3" aria-label="Legal navigation">
                  <a 
                    href="/terms" 
                    className="footer-link"
                    aria-label="Read terms of service"
                  >
                    Terms of Service
                  </a>
                  <a 
                    href="/privacy" 
                    className="footer-link"
                    aria-label="Read privacy policy"
                  >
                    Privacy Policy
                  </a>
                  <a 
                    href="/cookies" 
                    className="footer-link"
                    aria-label="Cookie policy"
                  >
                    Cookie Policy
                  </a>
                  <a 
                    href="/refunds" 
                    className="footer-link"
                    aria-label="Refund policy"
                  >
                    Refund Policy
                  </a>
                </nav>
              </div>
            </div>
          </div>

          {/* Social & Newsletter */}
          <div className="md:col-span-1">
            <h3 className="text-sm font-semibold text-white uppercase tracking-wider mb-4">
              Stay Connected
            </h3>
            
            {/* Social Links */}
            <div className="flex space-x-4 mb-6">
              <a 
                href="#" 
                className="social-link"
                aria-label="Follow us on Twitter"
              >
                <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
                  <title>Twitter</title>
                  <path d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84"/>
                </svg>
              </a>
              
              <a 
                href="#" 
                className="social-link"
                aria-label="Follow us on Instagram"
              >
                <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
                  <title>Instagram</title>
                  <path d="M12.017 0C5.396 0 .029 5.367.029 11.987c0 6.62 5.367 11.987 11.988 11.987s11.987-5.367 11.987-11.987C24.014 5.367 18.647.001 12.017.001zM8.449 16.988c-1.297 0-2.448-.49-3.323-1.297C4.198 14.895 3.708 13.744 3.708 12.447s.49-2.448 1.418-3.323c.875-.807 2.026-1.297 3.323-1.297s2.448.49 3.323 1.297c.928.875 1.418 2.026 1.418 3.323s-.49 2.448-1.418 3.244c-.875.807-2.026 1.297-3.323 1.297zm7.83-9.781c-.49 0-.928-.438-.928-.928 0-.49.438-.928.928-.928.49 0 .928.438.928.928 0 .49-.438.928-.928.928zm-3.832 9.244c-1.297 0-2.344-1.047-2.344-2.344s1.047-2.344 2.344-2.344 2.344 1.047 2.344 2.344-1.047 2.344-2.344 2.344z"/>
                </svg>
              </a>
              
              <a 
                href="#" 
                className="social-link"
                aria-label="Follow us on Facebook"
              >
                <svg className="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
                  <title>Facebook</title>
                  <path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z"/>
                </svg>
              </a>
            </div>

            {/* Newsletter Signup */}
            <div>
              <p className="text-sm text-gray-400 mb-3">
                Get notified about new events
              </p>
              <div className="flex">
                <input
                  type="email"
                  placeholder="Enter your email"
                  className="flex-1 px-3 py-2 bg-gray-800 border border-gray-700 rounded-l-md text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 text-sm"
                  aria-label="Email address for newsletter"
                />
                <button
                  type="button"
                  className="px-4 py-2 bg-indigo-600 text-white rounded-r-md hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 focus:ring-offset-gray-900 transition-colors duration-200 text-sm font-medium"
                  aria-label="Subscribe to newsletter"
                >
                  Subscribe
                </button>
              </div>
            </div>
          </div>
        </div>

        {/* Bottom Section */}
        <div className="mt-12 pt-8 border-t border-gray-800">
          <div className="flex flex-col md:flex-row md:justify-between md:items-center">
            {/* Copyright */}
            <div className="text-sm text-gray-400">
              <p>&copy; {new Date().getFullYear()} HVFLVSPOT. All rights reserved.</p>
            </div>

            {/* Additional Links */}
            <div className="mt-4 md:mt-0">
              <nav className="flex flex-wrap items-center space-x-6" aria-label="Footer utility navigation">
                <a 
                  href="/help" 
                  className="text-sm text-gray-400 hover:text-white transition-colors duration-200 focus:outline-none focus:ring-2 focus:ring-indigo-400 focus:ring-offset-2 focus:ring-offset-gray-900 rounded-md px-1"
                  aria-label="Get help and support"
                >
                  Help Center
                </a>
                <a 
                  href="/accessibility" 
                  className="text-sm text-gray-400 hover:text-white transition-colors duration-200 focus:outline-none focus:ring-2 focus:ring-indigo-400 focus:ring-offset-2 focus:ring-offset-gray-900 rounded-md px-1"
                  aria-label="Accessibility information"
                >
                  Accessibility
                </a>
                <a 
                  href="/sitemap" 
                  className="text-sm text-gray-400 hover:text-white transition-colors duration-200 focus:outline-none focus:ring-2 focus:ring-indigo-400 focus:ring-offset-2 focus:ring-offset-gray-900 rounded-md px-1"
                  aria-label="View sitemap"
                >
                  Sitemap
                </a>
              </nav>
            </div>
          </div>
        </div>
      </div>

      <style jsx>{`
        .footer-link {
          @apply block text-sm text-gray-400 hover:text-white transition-all duration-300 ease-out;
          @apply focus:outline-none focus:ring-2 focus:ring-indigo-400 focus:ring-offset-2 focus:ring-offset-gray-900 rounded-md px-1;
          @apply relative overflow-hidden;
        }

        .footer-link::before {
          content: '';
          position: absolute;
          bottom: 0;
          left: 0;
          width: 0;
          height: 1px;
          background: linear-gradient(90deg, #6366f1, #8b5cf6);
          transition: width 0.3s ease-out;
        }

        .footer-link:hover::before {
          width: 100%;
        }

        .social-link {
          @apply w-10 h-10 bg-gray-800 text-gray-400 rounded-full flex items-center justify-center;
          @apply hover:bg-indigo-600 hover:text-white transition-all duration-300 ease-out;
          @apply focus:outline-none focus:ring-2 focus:ring-indigo-400 focus:ring-offset-2 focus:ring-offset-gray-900;
          @apply transform hover:scale-110 hover:-translate-y-1;
        }

        .social-link:hover {
          box-shadow: 0 10px 25px rgba(99, 102, 241, 0.3);
        }

        /* Reduce motion for accessibility */
        @media (prefers-reduced-motion: reduce) {
          .footer-link,
          .social-link {
            transition: none !important;
            transform: none !important;
          }
          
          .footer-link::before {
            transition: none !important;
          }
          
          .social-link:hover {
            transform: none !important;
            box-shadow: none !important;
          }
        }
      `}</style>
    </footer>
  )
}

// src/lib/components/Footer.svelte
<footer class="bg-gray-900 text-white">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
    <div class="grid grid-cols-1 md:grid-cols-4 gap-8">
      <!-- Brand Section -->
      <div class="md:col-span-1">
        <a 
          href="/" 
          class="text-2xl font-bold text-white hover:text-indigo-300 transition-colors duration-300 focus:outline-none focus:ring-2 focus:ring-indigo-400 focus:ring-offset-2 focus:ring-offset-gray-900 rounded-md px-1"
          aria-label="HVFLVSPOT homepage"
        >
          HVFLVSPOT
        </a>
        <p class="mt-4 text-gray-400 text-sm leading-relaxed">
          Discover and book tickets for the best events near you. Your perfect experience is just a click away.
        </p>
      </div>

      <!-- Navigation Links -->
      <div class="md:col-span-2">
        <div class="grid grid-cols-2 gap-8">
          <!-- Company Links -->
          <div>
            <h3 class="text-sm font-semibold text-white uppercase tracking-wider mb-4">
              Company
            </h3>
            <nav class="space-y-3" aria-label="Company navigation">
              <a 
                href="/about" 
                class="footer-link"
                aria-label="Learn more about HVFLVSPOT"
              >
                About Us
              </a>
              <a 
                href="/contact" 
                class="footer-link"
                aria-label="Contact HVFLVSPOT support"
              >
                Contact
              </a>
              <a 
                href="/careers" 
                class="footer-link"
                aria-label="View career opportunities"
              >
                Careers
              </a>
              <a 
                href="/blog" 
                class="footer-link"
                aria-label="Read our blog"
              >
                Blog
              </a>
            </nav>
          </div>

          <!-- Legal Links -->
          <div>
            <h3 class="text-sm font-semibold text-white uppercase tracking-wider mb-4">
              Legal
            </h3>
            <nav class="space-y-3" aria-label="Legal navigation">
              <a 
                href="/terms" 
                class="footer-link"
                aria-label="Read terms of service"
              >
                Terms of Service
              </a>
              <a 
                href="/privacy" 
                class="footer-link"
                aria-label="Read privacy policy"
              >
                Privacy Policy
              </a>
              <a 
                href="/cookies" 
                class="footer-link"
                aria-label="Cookie policy"
              >
                Cookie Policy
              </a>
              <a 
                href="/refunds" 
                class="footer-link"
                aria-label="Refund policy"
              >
                Refund Policy
              </a>
            </nav>
          </div>
        </div>
      </div>

      <!-- Social & Newsletter -->
      <div class="md:col-span-1">
        <h3 class="text-sm font-semibold text-white uppercase tracking-wider mb-4">
          Stay Connected
        </h3>
        
        <!-- Social Links -->
        <div class="flex space-x-4 mb-6">
          <a 
            href="#" 
            class="social-link"
            aria-label="Follow us on Twitter"
          >
            <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
              <title>Twitter</title>
              <path d="M8.29 20.251c7.547 0 11.675-6.253 11.675-11.675 0-.178 0-.355-.012-.53A8.348 8.348 0 0022 5.92a8.19 8.19 0 01-2.357.646 4.118 4.118 0 001.804-2.27 8.224 8.224 0 01-2.605.996 4.107 4.107 0 00-6.993 3.743 11.65 11.65 0 01-8.457-4.287 4.106 4.106 0 001.27 5.477A4.072 4.072 0 012.8 9.713v.052a4.105 4.105 0 003.292 4.022 4.095 4.095 0 01-1.853.07 4.108 4.108 0 003.834 2.85A8.233 8.233 0 012 18.407a11.616 11.616 0 006.29 1.84"/>
            </svg>
          </a>
          
          <a 
            href="#" 
            class="social-link"
            aria-label="Follow us on Instagram"
          >
            <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
              <title>Instagram</title>
              <path d="M12.017 0C5.396 0 .029 5.367.029 11.987c0 6.62 5.367 11.987 11.988 11.987s11.987-5.367 11.987-11.987C24.014 5.367 18.647.001 12.017.001zM8.449 16.988c-1.297 0-2.448-.49-3.323-1.297C4.198 14.895 3.708 13.744 3.708 12.447s.49-2.448 1.418-3.323c.875-.807 2.026-1.297 3.323-1.297s2.448.49 3.323 1.297c.928.875 1.418 2.026 1.418 3.323s-.49 2.448-1.418 3.244c-.875.807-2.026 1.297-3.323 1.297zm7.83-9.781c-.49 0-.928-.438-.928-.928 0-.49.438-.928.928-.928.49 0 .928.438.928.928 0 .49-.438.928-.928.928zm-3.832 9.244c-1.297 0-2.344-1.047-2.344-2.344s1.047-2.344 2.344-2.344 2.344 1.047 2.344 2.344-1.047 2.344-2.344 2.344z"/>
            </svg>
          </a>
          
          <a 
            href="#" 
            class="social-link"
            aria-label="Follow us on Facebook"
          >
            <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 24 24">
              <title>Facebook</title>
              <path d="M24 12.073c0-6.627-5.373-12-12-12s-12 5.373-12 12c0 5.99 4.388 10.954 10.125 11.854v-8.385H7.078v-3.47h3.047V9.43c0-3.007 1.792-4.669 4.533-4.669 1.312 0 2.686.235 2.686.235v2.953H15.83c-1.491 0-1.956.925-1.956 1.874v2.25h3.328l-.532 3.47h-2.796v8.385C19.612 23.027 24 18.062 24 12.073z"/>
            </svg>
          </a>
        </div>

        <!-- Newsletter Signup -->
        <div>
          <p class="text-sm text-gray-400 mb-3">
            Get notified about new events
          </p>
          <div class="flex">
            <input
              type="email"
              placeholder="Enter your email"
              class="flex-1 px-3 py-2 bg-gray-800 border border-gray-700 rounded-l-md text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-indigo-500 text-sm"
              aria-label="Email address for newsletter"
            />
            <button
              type="button"
              class="px-4 py-2 bg-indigo-600 text-white rounded-r-md hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 focus:ring-offset-gray-900 transition-colors duration-200 text-sm font-medium"
              aria-label="Subscribe to newsletter"
            >
              Subscribe
            </button>
          </div>
        </div>
      </div>
    </div>

    <!-- Bottom Section -->
    <div class="mt-12 pt-8 border-t border-gray-800">
      <div class="flex flex-col md:flex-row md:justify-between md:items-center">
        <!-- Copyright -->
        <div class="text-sm text-gray-400">
          <p>&copy; {new Date().getFullYear()} HVFLVSPOT. All rights reserved.</p>
        </div>

        <!-- Additional Links -->
        <div class="mt-4 md:mt-0">
          <nav class="flex flex-wrap items-center space-x-6" aria-label="Footer utility navigation">
            <a 
              href="/help" 
              class="text-sm text-gray-400 hover:text-white transition-colors duration-200 focus:outline-none focus:ring-2 focus:ring-indigo-400 focus:ring-offset-2 focus:ring-offset-gray-900 rounded-md px-1"
              aria-label="Get help and support"
            >
              Help Center
            </a>
            <a 
              href="/accessibility" 
              class="text-sm text-gray-400 hover:text-white transition-colors duration-200 focus:outline-none focus:ring-2 focus:ring-indigo-400 focus:ring-offset-2 focus:ring-offset-gray-900 rounded-md px-1"
              aria-label="Accessibility information"
            >
              Accessibility
            </a>
            <a 
              href="/sitemap" 
              class="text-sm text-gray-400 hover:text-white transition-colors duration-200 focus:outline-none focus:ring-2 focus:ring-indigo-400 focus:ring-offset-2 focus:ring-offset-gray-900 rounded-md px-1"
              aria-label="View sitemap"
            >
              Sitemap
            </a>
          </nav>
        </div>
      </div>
    </div>
  </div>
</footer>

<style>
  .footer-link {
    @apply block text-sm text-gray-400 hover:text-white transition-all duration-300 ease-out;
    @apply focus:outline-none focus:ring-2 focus:ring-indigo-400 focus:ring-offset-2 focus:ring-offset-gray-900 rounded-md px-1;
    @apply relative overflow-hidden;
  }

  .footer-link::before {
    content: '';
    position: absolute;
    bottom: 0;
    left: 0;
    width: 0;
    height: 1px;
    background: linear-gradient(90deg, #6366f1, #8b5cf6);
    transition: width 0.3s ease-out;
  }

  .footer-link:hover::before {
    width: 100%;
  }

  .social-link {
    @apply w-10 h-10 bg-gray-800 text-gray-400 rounded-full flex items-center justify-center;
    @apply hover:bg-indigo-600 hover:text-white transition-all duration-300 ease-out;
    @apply focus:outline-none focus:ring-2 focus:ring-indigo-400 focus:ring-offset-2 focus:ring-offset-gray-900;
    @apply transform hover:scale-110 hover:-translate-y-1;
  }

  .social-link:hover {
    box-shadow: 0 10px 25px rgba(99, 102, 241, 0.3);
  }

  /* Reduce motion for accessibility */
  @media (prefers-reduced-motion: reduce) {
    .footer-link,
    .social-link {
      transition: none !important;
      transform: none !important;
    }
    
    .footer-link::before {
      transition: none !important;
    }
    
    .social-link:hover {
      transform: none !important;
      box-shadow: none !important;
    }
  }
</style>
